[[fixture]]
name = "Left"
universe = 1
pan = 178
fpan = 179
tilt = 180
ftilt = 181
uid = "left-fixture"

[[fixture]]
name = "Right"
universe = 1
pan = 217
fpan = 218
tilt = 219
ftilt = 220
uid = "right-fixture"
