[[fixture]]
name = "Left"
universe = 1
pan = 178
fpan = 179
tilt = 180
ftilt = 181
uid = "left-fixture"
min_pan = 24300
max_pan = 18200
min_tilt = 20000
max_tilt = 16000

[[fixture]]
name = "Right"
universe = 1
pan = 217
fpan = 218
tilt = 219
ftilt = 220
uid = "right-fixture"
min_pan = 25800
max_pan = 19800
min_tilt = 20500
max_tilt = 16000
