// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlertDialog(arg1, arg2) {
  return window['go']['main']['App']['AlertDialog'](arg1, arg2);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function GetLastSessionInfo() {
  return window['go']['main']['App']['GetLastSessionInfo']();
}

export function GetSACNConfig() {
  return window['go']['main']['App']['GetSACNConfig']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function LoadFileFromPath(arg1) {
  return window['go']['main']['App']['LoadFileFromPath'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SetCalibrationPoints(arg1) {
  return window['go']['main']['App']['SetCalibrationPoints'](arg1);
}

export function SetFixtures(arg1) {
  return window['go']['main']['App']['SetFixtures'](arg1);
}

export function SetMouseForAllFixtures(arg1, arg2) {
  return window['go']['main']['App']['SetMouseForAllFixtures'](arg1, arg2);
}

export function SetPanTiltForFixture(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPanTiltForFixture'](arg1, arg2, arg3);
}

export function SetSACNConfig(arg1) {
  return window['go']['main']['App']['SetSACNConfig'](arg1);
}

export function TypeExporter(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TypeExporter'](arg1, arg2, arg3, arg4, arg5, arg6);
}
