// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveUniverse(arg1) {
  return window['go']['main']['App']['ActiveUniverse'](arg1);
}

export function AlertDialog(arg1, arg2) {
  return window['go']['main']['App']['AlertDialog'](arg1, arg2);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function DeactiveUniverse(arg1) {
  return window['go']['main']['App']['DeactiveUniverse'](arg1);
}

export function SendForAllFromMouse(arg1, arg2) {
  return window['go']['main']['App']['SendForAllFromMouse'](arg1, arg2);
}

export function SendPanTilt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPanTilt'](arg1, arg2, arg3);
}

export function SetCalibrationPoints(arg1) {
  return window['go']['main']['App']['SetCalibrationPoints'](arg1);
}

export function SetFixtures(arg1) {
  return window['go']['main']['App']['SetFixtures'](arg1);
}

export function TypeExporter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TypeExporter'](arg1, arg2, arg3, arg4);
}
