// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetCalibrationPoints(arg1) {
  return window['go']['main']['Folje']['SetCalibrationPoints'](arg1);
}

export function SetFixtures(arg1) {
  return window['go']['main']['Folje']['SetFixtures'](arg1);
}

export function TypeExporter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Folje']['TypeExporter'](arg1, arg2, arg3, arg4);
}
