// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SetCalibrationPoints(arg1:{[key: string]: main.CalibrationPoint}):Promise<void>;

export function SetFixtures(arg1:Array<main.Fixture>):Promise<void>;

export function TypeExporter(arg1:main.Point,arg2:main.CalibrationPoint,arg3:main.CalibratedCalibrationPoint,arg4:main.Fixture):Promise<void>;
